# Generated by Django 5.1.5 on 2025-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='загрузите фото книги')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name='укажите описание книги')),
                ('price', models.PositiveIntegerField(default=20, verbose_name='укажите цену книги')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='укажите дату выхода книги')),
                ('genre', models.CharField(choices=[('FANTASY', 'FANTASY'), ('MYSTERY', 'MYSTERY'), ('ROMANCE', 'ROMANCE')], default='FANTASY', max_length=20, verbose_name='укажите жанр книги')),
                ('mail', models.CharField(max_length=100, verbose_name='укажите почту автора книги')),
                ('audio_book', models.URLField(verbose_name='укажите ссылку из YOUTUBE на аудиокнигу')),
            ],
        ),
    ]
