# Generated by Django 5.1.5 on 2025-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default='Чингиз Айтматов', max_length=100, verbose_name='укажите автора книги'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
